feat(test): test initramfs
faast-rt/lambdo pull request #8
Opened 2023-10-24 07:14 UTC by WoodenMaiden

2023-10-24 13:21 UTC, lucido-simon commented
Hi! Thanks for the PR. Can you squash the two commits together please ?

2023-10-27 09:05 UTC, alexis-langlet requested changes
Nice work
The only real issue of all this is that you don't use mocks as mocks but as different implementations

2023-10-30 09:06 UTC, alexis-langlet commented on initramfs/src/image.rs
> +            MockFileHandler::create(path)
There could be some problems if someone needs to change create() behaviour 

```suggestion
            Ok(Self {
                path: path.to_string(),
            })
```

2023-10-30 09:06 UTC, alexis-langlet commented on initramfs/src/image.rs
> +            }
This part seems a bit weird to me, it would be nice having Simon's POV on this

2023-10-30 12:24 UTC, alexis-langlet submitted a review, later dismissed
Really nice job, thank you

2023-11-04 10:03 UTC, lucido-simon requested changes
LGTM, except a few formatting nits. gj !

2023-11-04 10:03 UTC, lucido-simon commented on initramfs/src/image.rs
> +}
```suggestion
pub trait FileHandler: Write + Read + Sized {
    fn create(path: &str) -> Result<Self>;
    fn open(path: &str) -> Result<Self>;
}
```

Looks cleaner imo

2023-11-04 10:03 UTC, lucido-simon commented on initramfs/src/image.rs
> +            <Handler>::create(&file_name)
```suggestion
            Handler::create(&file_name)
```

2023-11-04 10:03 UTC, lucido-simon commented on initramfs/src/image.rs
> +        let mut init_file = <Handler>::open(init_path)
```suggestion
        let mut init_file = Handler::open(init_path)
```

Probably need to run `rustfmt` after that, it's probably not going to format it the same way.

2023-11-04 10:03 UTC, lucido-simon commented on initramfs/src/image.rs
> +        let mut agent_file = <Handler>::open(agent_path)
```suggestion
        let mut agent_file = Handler::open(agent_path)
```

Same

2023-11-04 10:03 UTC, lucido-simon commented on initramfs/src/image.rs
> +        let mut agent_config_file = <Handler>::open(agent_config_path)
```suggestion
        let mut agent_config_file = Handler::open(agent_config_path)
```
Same

2023-11-05 14:57 UTC, lucido-simon commented
I've taken the liberty of making a small change: renaming `blobSum` of the `LayerMetadata` struct to `blob_sum`. This allows removing the `#[allow(non_snake_case)]`, by replacing it by `#[serde(rename_all = "camelCase")]` in `image.rs`.

Other than that, PR LGTM.

2023-11-05 14:58 UTC, lucido-simon approved these changes

2023-11-05 14:59 UTC, merged